---
###############################################################################
# . cpanel.yml - cPanel Deployment Configuration File
# 
# Description:   Automates deployment of Streamity IPTV Web Player to cPanel. 
#              Builds the React application and deploys static files plus
#              PHP backend to public_html root directory.
#
# Repository:  irlam/webplayer
# Application: Streamity. tv v2 Xtream IPTV Player
# Created: 10/01/2026 (UK format: DD/MM/YYYY)
# Updated: 11/01/2026 - Fixed file paths and deployment structure
#
# How it works:
# 1. Installs Node.js dependencies
# 2. Builds the React application for production
# 3. Deploys built files to public_html ROOT (not subfolder)
# 4. Copies PHP backend files
# 5. Sets up error logging
###############################################################################

deployment:
  tasks:
    # Task 1: Define deployment paths
    - export DEPLOYPATH=/home/omxfcmit/public_html
    - export REPOPATH=/home/omxfcmit/repositories/webplayer
    
    # Task 2: Navigate to repository
    - cd $REPOPATH
    
    # Task 3: Install dependencies
    - /usr/bin/npm install
    
    # Task 4: Build React application
    - export GENERATE_SOURCEMAP=false
    - /usr/bin/npm run build
    
    # Task 5: Create logs directory
    - /bin/mkdir -p $DEPLOYPATH/logs
    
    # Task 6: Backup and clean deployment directory
    # Keep important files:  . htaccess, logs, cgi-bin, error_log
    - /bin/find $DEPLOYPATH -maxdepth 1 -type f !  -name '. htaccess' ! -name 'error_log' ! -name '.*' -delete 2>/dev/null || true
    - /bin/find $DEPLOYPATH -maxdepth 1 -type d ! -name 'cgi-bin' ! -name 'logs' ! -name '.' ! -name '..' !  -name 'public_html' -exec rm -rf {} + 2>/dev/null || true
    
    # Task 7: Deploy built React files from build folder
    - /bin/cp -R $REPOPATH/build/* $DEPLOYPATH/
    
    # Task 8: Create error log files
    - /bin/touch $DEPLOYPATH/logs/php_errors.log
    - /bin/touch $DEPLOYPATH/logs/app_errors.log
    - /bin/touch $DEPLOYPATH/logs/database_errors.log
    - /bin/touch $DEPLOYPATH/logs/deployment. log
    
    # Task 9: Log deployment
    - echo "[$(date '+%d/%m/%Y %H:%M:%S')] Deployment completed" >> $DEPLOYPATH/logs/deployment.log
    
    # Task 10: Set permissions
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/*. php 2>/dev/null || true
    - /bin/chmod 644 $DEPLOYPATH/*. js 2>/dev/null || true
    - /bin/chmod -R 666 $DEPLOYPATH/logs/*. log 2>/dev/null || true
    
    # Task 11: Create . htaccess with proper configuration
    - |
      /bin/cat > $DEPLOYPATH/.htaccess << 'EOF'
      # . htaccess for Streamity Player
      # Generated:  11/01/2026
      
      # PHP Error Logging
      php_flag display_errors Off
      php_flag log_errors On
      php_value error_log /home/omxfcmit/public_html/logs/php_errors.log
      php_value error_reporting E_ALL
      
      # Enable PHP
      AddHandler application/x-httpd-php .php
      
      # React Router Support
      <IfModule mod_rewrite. c>
        RewriteEngine On
        RewriteBase /
        
        # Don't rewrite PHP files
        RewriteCond %{REQUEST_FILENAME} !\. php$
        
        # Don't rewrite logs
        RewriteCond %{REQUEST_URI} !^/logs/
        
        # Don't rewrite existing files
        RewriteCond %{REQUEST_FILENAME} ! -f
        RewriteCond %{REQUEST_FILENAME} !-d
        
        # Redirect to index.html
        RewriteRule .  /index.html [L]
      </IfModule>
      
      # Protect logs directory
      <DirectoryMatch "^/. */logs/">
        Order deny,allow
        Deny from all
      </DirectoryMatch>
      
      <FilesMatch "\.(log)$">
        Order deny,allow
        Deny from all
      </FilesMatch>
      
      # GZIP Compression
      <IfModule mod_deflate.c>
        AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
      </IfModule>
      
      # Browser Caching
      <IfModule mod_expires.c>
        ExpiresActive On
        ExpiresByType image/jpg "access plus 1 year"
        ExpiresByType image/jpeg "access plus 1 year"
        ExpiresByType image/gif "access plus 1 year"
        ExpiresByType image/png "access plus 1 year"
        ExpiresByType text/css "access plus 1 month"
        ExpiresByType application/javascript "access plus 1 month"
        ExpiresByType text/html "access plus 0 seconds"
      </IfModule>
      
      # Security Headers
      <IfModule mod_headers.c>
        Header set X-Content-Type-Options "nosniff"
        Header set X-Frame-Options "SAMEORIGIN"
        Header set X-XSS-Protection "1; mode=block"
      </IfModule>
      EOF
