---
###############################################################################
# . cpanel.yml - cPanel Deployment Configuration File
# 
# Description: This file automates the deployment of the webplayer React app
#              to cPanel hosting.  It builds the React application and deploys
#              the static files to the public_html directory.
#
# Repository: irlam/webplayer
# Application:  IPTV Editor Player (React Application)
# Created: 10/01/2026
# Format: UK date format (DD/MM/YYYY)
#
# How it works:
# 1. Installs Node.js dependencies using npm
# 2. Builds the React application for production
# 3. Copies the built files to the web server's public directory
# 4. Cleans up unnecessary files to save space
#
# Note:  Ensure your cPanel account has Node.js enabled and sufficient resources
###############################################################################

deployment:
  tasks:
    # Task 1: Install Node.js dependencies
    # This downloads and installs all required packages listed in package.json
    - export DEPLOYPATH=/home/YOUR_CPANEL_USERNAME/public_html
    - export REPOPATH=/home/YOUR_CPANEL_USERNAME/repositories/webplayer
    
    # Navigate to the repository directory
    - cd $REPOPATH
    
    # Install dependencies using npm
    # The --production flag skips development dependencies
    - /usr/bin/npm install --production
    
    # Task 2: Build the React application
    # This creates optimized production files in the 'build' folder
    # GENERATE_SOURCEMAP=false prevents source maps from being created (saves space)
    - export GENERATE_SOURCEMAP=false
    - /usr/bin/npm run build
    
    # Task 3: Clean the deployment directory
    # Remove old files from public_html (except .htaccess and other hidden files)
    - /bin/find $DEPLOYPATH -maxdepth 1 -type f !  -name '. htaccess' !  -name '. env' ! -name '.*' -delete
    - /bin/find $DEPLOYPATH -maxdepth 1 -type d ! -name 'cgi-bin' ! -name '.' ! -name '..' ! -name 'public_html' -exec rm -rf {} + 2>/dev/null || true
    
    # Task 4: Copy built files to deployment directory
    # This copies all files from the build folder to public_html
    - /bin/cp -R $REPOPATH/build/* $DEPLOYPATH/
    
    # Task 5: Set proper permissions
    # Ensures files are readable by the web server
    - /bin/chmod -R 755 $DEPLOYPATH
    
    # Task 6: Create .htaccess for React Router support
    # This ensures that React Router works properly with direct URL access
    - |
      /bin/cat > $DEPLOYPATH/.htaccess << 'EOF'
      # . htaccess for React Router
      # Generated:  10/01/2026
      
      <IfModule mod_rewrite. c>
        RewriteEngine On
        RewriteBase /
        
        # Redirect all requests to index.html except for existing files
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-l
        RewriteRule .  /index.html [L]
      </IfModule>
      
      # Enable GZIP compression
      <IfModule mod_deflate.c>
        AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
      </IfModule>
      
      # Set caching headers for static assets
      <IfModule mod_expires.c>
        ExpiresActive On
        ExpiresByType image/jpg "access plus 1 year"
        ExpiresByType image/jpeg "access plus 1 year"
        ExpiresByType image/gif "access plus 1 year"
        ExpiresByType image/png "access plus 1 year"
        ExpiresByType image/svg+xml "access plus 1 year"
        ExpiresByType text/css "access plus 1 month"
        ExpiresByType application/javascript "access plus 1 month"
        ExpiresByType application/pdf "access plus 1 month"
        ExpiresByType text/html "access plus 0 seconds"
      </IfModule>
      EOF
